const quotes = [
  {
    id: 1,
    name: "The only way to learn mathematics is to do mathematics.",
    nameVi: "Cách duy nhất để học toán là làm toán.",
    tag: "mathematics",
  },
  {
    id: 2,
    name: "Education is the most powerful weapon which you can use to change the world.",
    nameVi: "Giáo dục là vũ khí mạnh mẽ nhất mà bạn có thể sử dụng để thay đổi thế giới.",
    tag: "education",
  },
  {
    id: 3,
    name: "The beautiful thing about learning is that no one can take it away from you.",
    nameVi: "Điều tuyệt vời của việc học tập là không ai có thể lấy đi kiến thức từ bạn.",
    tag: "knowledge",
  },
  {
    id: 4,
    name: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    nameVi: "Thành công không phải là điểm cuối, thất bại không phải là chết người: điều quan trọng là can đảm để tiếp tục.",
    tag: "perseverance",
  },
  {
    id: 5,
    name: "The expert in anything was once a beginner.",
    nameVi: "Người chuyên gia trong bất kỳ lĩnh vực nào cũng từng là người mới bắt đầu.",
    tag: "growth",
  },
  {
    id: 6,
    name: "Learning never exhausts the mind.",
    nameVi: "Học tập không bao giờ làm kiệt quệ tâm trí.",
    tag: "mindset",
  },
  {
    id: 7,
    name: "The more that you read, the more things you will know. The more that you learn, the more places you'll go.",
    nameVi: "Bạn đọc càng nhiều, bạn sẽ biết càng nhiều điều. Bạn học càng nhiều, bạn sẽ đến được càng nhiều nơi.",
    tag: "reading",
  },
  {
    id: 8,
    name: "It does not matter how slowly you go as long as you do not stop.",
    nameVi: "Không quan trọng bạn đi chậm như thế nào miễn là bạn không dừng lại.",
    tag: "persistence",
  },
  {
    id: 9,
    name: "The only impossible journey is the one you never begin.",
    nameVi: "Hành trình bất khả thi duy nhất là hành trình bạn không bao giờ bắt đầu.",
    tag: "motivation",
  },
  {
    id: 10,
    name: "Learning is a treasure that will follow its owner everywhere.",
    nameVi: "Học tập là kho báu sẽ theo chủ nhân đi khắp mọi nơi.",
    tag: "wisdom",
  },
  {
    id: 11,
    name: "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.",
    nameVi: "Khả năng học là một món quà; kỹ năng học là một tài năng; sự sẵn lòng học là một lựa chọn.",
    tag: "choice",
  },
  {
    id: 12,
    name: "Don't let what you cannot do interfere with what you can do.",
    nameVi: "Đừng để những gì bạn không thể làm cản trở những gì bạn có thể làm.",
    tag: "focus",
  },
  {
    id: 13,
    name: "The best time to plant a tree was 20 years ago. The second best time is now.",
    nameVi: "Thời điểm tốt nhất để trồng cây là 20 năm trước. Thời điểm tốt thứ hai là bây giờ.",
    tag: "action",
  },
  {
    id: 14,
    name: "Believe you can and you're halfway there.",
    nameVi: "Tin rằng bạn có thể và bạn đã hoàn thành được một nửa chặng đường.",
    tag: "belief",
  },
  {
    id: 15,
    name: "Intelligence plus character - that is the goal of true education.",
    nameVi: "Trí tuệ cộng với nhân cách - đó là mục tiêu của giáo dục thực sự.",
    tag: "character",
  },
  {
    id: 16,
    name: "Study hard what interests you the most in the most undisciplined, irreverent and original manner possible.",
    nameVi: "Hãy học chăm chỉ những gì bạn quan tâm nhất theo cách tự do, không kiềm chế và độc đáo nhất có thể.",
    tag: "passion",
  },
  {
    id: 17,
    name: "The mind is not a vessel to be filled, but a fire to be kindled.",
    nameVi: "Tâm trí không phải là cái bình để đổ đầy, mà là ngọn lửa cần được thắp sáng.",
    tag: "inspiration",
  },
  {
    id: 18,
    name: "Failure is the opportunity to begin again more intelligently.",
    nameVi: "Thất bại là cơ hội để bắt đầu lại một cách thông minh hơn.",
    tag: "failure",
  },
  {
    id: 19,
    name: "The journey of a thousand miles begins with one step.",
    nameVi: "Hành trình nghìn dặm bắt đầu bằng một bước chân.",
    tag: "journey",
  },
  {
    id: 20,
    name: "What we learn with pleasure we never forget.",
    nameVi: "Những gì chúng ta học với niềm vui, chúng ta sẽ không bao giờ quên.",
    tag: "joy",
  },
  {
    id: 21,
    name: "Knowledge is power.",
    nameVi: "Kiến thức là sức mạnh.",
    tag: "power",
  },
  {
    id: 22,
    name: "The roots of education are bitter, but the fruit is sweet.",
    nameVi: "Gốc rễ của giáo dục có vị đắng, nhưng quả của nó thì ngọt ngào.",
    tag: "reward",
  },
  {
    id: 23,
    name: "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    nameVi: "Hãy sống như thể ngày mai bạn sẽ chết. Hãy học như thể bạn sẽ sống mãi mãi.",
    tag: "learning",
  },
  {
    id: 24,
    name: "An investment in knowledge pays the best interest.",
    nameVi: "Đầu tư vào kiến thức sẽ mang lại lợi ích tốt nhất.",
    tag: "investment",
  },
  {
    id: 25,
    name: "The only source of knowledge is experience.",
    nameVi: "Nguồn duy nhất của kiến thức là kinh nghiệm.",
    tag: "experience",
  },
  {
    id: 26,
    name: "Education is not preparation for life; education is life itself.",
    nameVi: "Giáo dục không phải là sự chuẩn bị cho cuộc sống; giáo dục chính là cuộc sống.",
    tag: "life",
  },
  {
    id: 27,
    name: "The more I learn, the more I realize I don't know.",
    nameVi: "Tôi càng học nhiều, tôi càng nhận ra mình không biết nhiều.",
    tag: "humility",
  },
  {
    id: 28,
    name: "A mind that is stretched by a new experience can never go back to its old dimensions.",
    nameVi: "Tâm trí được mở rộng bởi trải nghiệm mới sẽ không bao giờ có thể quay về kích thước cũ.",
    tag: "growth",
  },
  {
    id: 29,
    name: "Tell me and I forget, teach me and I may remember, involve me and I learn.",
    nameVi: "Nói với tôi và tôi sẽ quên, dạy tôi và tôi có thể nhớ, để tôi tham gia và tôi sẽ học được.",
    tag: "involvement",
  },
  {
    id: 30,
    name: "The best teacher is the one who suggests rather than dogmatizes, and inspires his listener with the wish to teach himself.",
    nameVi: "Giáo viên tốt nhất là người gợi ý thay vì áp đặt, và truyền cảm hứng cho người nghe mong muốn tự dạy mình.",
    tag: "teaching",
  },
  {
    id: 31,
    name: "Learning without thinking is useless, but thinking without learning is dangerous.",
    nameVi: "Học mà không suy nghĩ thì vô ích, nhưng suy nghĩ mà không học thì nguy hiểm.",
    tag: "thinking",
  },
  {
    id: 32,
    name: "Study without desire spoils the memory, and it retains nothing that it takes in.",
    nameVi: "Học tập mà không có ham muốn sẽ làm hỏng trí nhớ, và nó sẽ không giữ lại gì mà nó tiếp nhận.",
    tag: "desire",
  },
  {
    id: 33,
    name: "Education is the key to unlocking the world, a passport to freedom.",
    nameVi: "Giáo dục là chìa khóa để mở khóa thế giới, là hộ chiếu dẫn đến tự do.",
    tag: "freedom",
  },
  {
    id: 34,
    name: "The whole purpose of education is to turn mirrors into windows.",
    nameVi: "Mục đích toàn bộ của giáo dục là biến gương thành cửa sổ.",
    tag: "perspective",
  },
  {
    id: 35,
    name: "I have not failed. I've just found 10,000 ways that won't work.",
    nameVi: "Tôi không thất bại. Tôi chỉ tìm ra 10.000 cách không hiệu quả.",
    tag: "persistence",
  },
  {
    id: 36,
    name: "The difference between ordinary and extraordinary is that little extra.",
    nameVi: "Sự khác biệt giữa bình thường và phi thường là chút nỗ lực thêm đó.",
    tag: "effort",
  },
  {
    id: 37,
    name: "Success is the sum of small efforts, repeated day in and day out.",
    nameVi: "Thành công là tổng của những nỗ lực nhỏ, được lặp đi lặp lại ngày này qua ngày khác.",
    tag: "consistency",
  },
  {
    id: 38,
    name: "The only way to do great work is to love what you do.",
    nameVi: "Cách duy nhất để làm được công việc tuyệt vời là yêu thích những gì bạn làm.",
    tag: "passion",
  },
  {
    id: 39,
    name: "Don't be afraid to give up the good to go for the great.",
    nameVi: "Đừng ngại từ bỏ cái tốt để hướng đến cái tuyệt vời.",
    tag: "ambition",
  },
  {
    id: 40,
    name: "The future belongs to those who believe in the beauty of their dreams.",
    nameVi: "Tương lai thuộc về những ai tin vào vẻ đẹp của ước mơ mình.",
    tag: "dreams",
  },
  {
    id: 41,
    name: "It is during our darkest moments that we must focus to see the light.",
    nameVi: "Chính trong những khoảnh khắc tăm tối nhất, chúng ta phải tập trung để nhìn thấy ánh sáng.",
    tag: "hope",
  },
  {
    id: 42,
    name: "The way to get started is to quit talking and begin doing.",
    nameVi: "Cách để bắt đầu là ngừng nói và bắt đầu hành động.",
    tag: "action",
  },
  {
    id: 43,
    name: "Your limitation—it's only your imagination.",
    nameVi: "Giới hạn của bạn chỉ là trí tưởng tượng của bạn.",
    tag: "imagination",
  },
  {
    id: 44,
    name: "Great things never come from comfort zones.",
    nameVi: "Những điều tuyệt vời không bao giờ đến từ vùng an toàn.",
    tag: "comfort_zone",
  },
  {
    id: 45,
    name: "Dream it. Wish it. Do it.",
    nameVi: "Mơ về nó. Ước về nó. Làm nó.",
    tag: "motivation",
  },
  {
    id: 46,
    name: "Success doesn't just find you. You have to go out and get it.",
    nameVi: "Thành công không tự tìm đến bạn. Bạn phải ra ngoài và giành lấy nó.",
    tag: "pursuit",
  },
  {
    id: 47,
    name: "The harder you work for something, the greater you'll feel when you achieve it.",
    nameVi: "Bạn càng làm việc chăm chỉ cho một điều gì đó, bạn sẽ càng cảm thấy tuyệt vời khi đạt được nó.",
    tag: "hard_work",
  },
  {
    id: 48,
    name: "Dream bigger. Do bigger.",
    nameVi: "Mơ lớn hơn. Làm lớn hơn.",
    tag: "ambition",
  },
  {
    id: 49,
    name: "Don't stop when you're tired. Stop when you're done.",
    nameVi: "Đừng dừng lại khi bạn mệt. Hãy dừng lại khi bạn hoàn thành.",
    tag: "determination",
  },
  {
    id: 50,
    name: "Wake up with determination. Go to bed with satisfaction.",
    nameVi: "Thức dậy với quyết tâm. Đi ngủ với sự hài lòng.",
    tag: "daily_motivation",
  },
  {
    id: 51,
    name: "Do something today that your future self will thank you for.",
    nameVi: "Hãy làm điều gì đó hôm nay mà bản thân tương lai của bạn sẽ cảm ơn.",
    tag: "future",
  },
  {
    id: 52,
    name: "Little things make big days.",
    nameVi: "Những điều nhỏ tạo nên những ngày lớn.",
    tag: "small_steps",
  },
  {
    id: 53,
    name: "It's going to be hard, but hard does not mean impossible.",
    nameVi: "Nó sẽ khó khăn, nhưng khó khăn không có nghĩa là bất khả thi.",
    tag: "difficulty",
  },
  {
    id: 54,
    name: "Don't wait for opportunity. Create it.",
    nameVi: "Đừng chờ đợi cơ hội. Hãy tạo ra nó.",
    tag: "opportunity",
  },
  {
    id: 55,
    name: "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
    nameVi: "Đôi khi chúng ta được thử thách không phải để thể hiện điểm yếu, mà để khám phá sức mạnh của mình.",
    tag: "strength",
  },
  {
    id: 56,
    name: "The key to success is to focus on goals, not obstacles.",
    nameVi: "Chìa khóa thành công là tập trung vào mục tiêu, không phải ch장애물.",
    tag: "focus",
  },
  {
    id: 57,
    name: "Dream it. Believe it. Build it.",
    nameVi: "Mơ về nó. Tin vào nó. Xây dựng nó.",
    tag: "building",
  },
  {
    id: 58,
    name: "If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work.",
    nameVi: "Nếu bạn muốn đạt được sự xuất sắc, bạn có thể đến đó ngay hôm nay. Từ giây phút này, hãy ngừng làm những công việc kém xuất sắc.",
    tag: "excellence",
  },
  {
    id: 59,
    name: "A year from now you may wish you had started today.",
    nameVi: "Một năm từ bây giờ bạn có thể ước rằng mình đã bắt đầu từ hôm nay.",
    tag: "timing",
  },
  {
    id: 60,
    name: "The only person you are destined to become is the person you decide to be.",
    nameVi: "Người duy nhất bạn định trở thành là người mà bạn quyết định trở thành.",
    tag: "self_determination",
  },
  {
    id: 61,
    name: "Education is not filling a bucket but lighting a fire.",
    nameVi: "Giáo dục không phải là đổ đầy một cái xô mà là thắp sáng ngọn lửa.",
    tag: "inspiration",
  },
  {
    id: 62,
    name: "The only thing that interferes with my learning is my education.",
    nameVi: "Điều duy nhất can thiệp vào việc học của tôi là nền giáo dục của tôi.",
    tag: "creativity",
  },
  {
    id: 63,
    name: "I am always doing that which I cannot do, in order that I may learn how to do it.",
    nameVi: "Tôi luôn làm những điều mà tôi không thể làm, để có thể học cách làm nó.",
    tag: "challenge",
  },
  {
    id: 64,
    name: "Learning is not attained by chance, it must be sought for with ardor and diligence.",
    nameVi: "Học tập không đạt được một cách tình cờ, nó phải được tìm kiếm bằng sự nhiệt tình và siêng năng.",
    tag: "diligence",
  },
  {
    id: 65,
    name: "The important thing is not to stop questioning.",
    nameVi: "Điều quan trọng là không ngừng đặt câu hỏi.",
    tag: "questioning",
  },
  {
    id: 66,
    name: "I never teach my pupils, I only attempt to provide the conditions in which they can learn.",
    nameVi: "Tôi không bao giờ dạy học sinh của mình, tôi chỉ cố gắng tạo ra điều kiện để họ có thể học.",
    tag: "conditions",
  },
  {
    id: 67,
    name: "You don't learn to walk by following rules. You learn by doing, and by falling over.",
    nameVi: "Bạn không học đi bằng cách tuân theo quy tắc. Bạn học bằng cách thực hành và bằng cách ngã.",
    tag: "practice",
  },
  {
    id: 68,
    name: "The beautiful thing about learning is nobody can take it away from you.",
    nameVi: "Điều đẹp đẽ của việc học tập là không ai có thể lấy đi nó từ bạn.",
    tag: "permanence",
  },
  {
    id: 69,
    name: "Learning is the only thing the mind never exhausts, never fears, and never regrets.",
    nameVi: "Học tập là điều duy nhất mà tâm trí không bao giờ kiệt sức, không bao giờ sợ hãi và không bao giờ hối tiếc.",
    tag: "mind",
  },
  {
    id: 70,
    name: "The illiterate of the 21st century will not be those who cannot read and write, but those who cannot learn, unlearn, and relearn.",
    nameVi: "Những người mù chữ của thế kỷ 21 sẽ không phải là những người không biết đọc và viết, mà là những người không thể học, quên và học lại.",
    tag: "adaptability",
  },
  {
    id: 71,
    name: "It is impossible for a man to learn what he thinks he already knows.",
    nameVi: "Không thể nào một người học được điều mà anh ta nghĩ mình đã biết.",
    tag: "humility",
  },
  {
    id: 72,
    name: "Learning never exhausts the mind because there is always more to discover.",
    nameVi: "Học tập không bao giờ làm kiệt sức tâm trí vì luôn có nhiều điều để khám phá.",
    tag: "discovery",
  },
  {
    id: 73,
    name: "The more you know, the more you know you don't know.",
    nameVi: "Bạn càng biết nhiều, bạn càng biết mình không biết nhiều.",
    tag: "awareness",
  },
  {
    id: 74,
    name: "A good teacher can inspire hope, ignite the imagination, and instill a love of learning.",
    nameVi: "Một giáo viên giỏi có thể truyền cảm hứng hy vọng, khơi dậy trí tưởng tượng và thấm nhuần tình yêu học tập.",
    tag: "teaching",
  },
  {
    id: 75,
    name: "Education is the passport to the future, for tomorrow belongs to those who prepare for it today.",
    nameVi: "Giáo dục là hộ chiếu đến tương lai, vì ngày mai thuộc về những ai chuẩn bị cho nó ngày hôm nay.",
    tag: "preparation",
  },
  {
    id: 76,
    name: "The function of education is to teach one to think intensively and to think critically.",
    nameVi: "Chức năng của giáo dục là dạy một người suy nghĩ chuyên sâu và suy nghĩ phản biện.",
    tag: "critical_thinking",
  },
  {
    id: 77,
    name: "Develop a passion for learning. If you do, you will never cease to grow.",
    nameVi: "Hãy phát triển niềm đam mê học tập. Nếu bạn làm vậy, bạn sẽ không bao giờ ngừng phát triển.",
    tag: "passion",
  },
  {
    id: 78,
    name: "The best students are those who never quite believe their teachers.",
    nameVi: "Những học sinh tốt nhất là những người không hoàn toàn tin tưởng giáo viên của họ.",
    tag: "skepticism",
  },
  {
    id: 79,
    name: "I study all the time. Only until my last breath, I stop studying.",
    nameVi: "Tôi học tập mọi lúc. Chỉ đến hơi thở cuối cùng, tôi mới thôi học",
    tag: "lifelong",
  },
  {
    id: 80,
    name: "Change is the end result of all true learning.",
    nameVi: "Thay đổi là kết quả cuối cùng của mọi việc học tập thực sự.",
    tag: "change",
  },
  {
    id: 81,
    name: "The purpose of learning is growth, and our minds, unlike our bodies, can continue growing as we continue to live.",
    nameVi:
      "Mục đích của việc học tập là phát triển, và tâm trí chúng ta, không giống như cơ thể, có thể tiếp tục phát triển khi chúng ta tiếp tục sống.",
    tag: "growth",
  },
  {
    id: 82,
    name: "Study hard, for the well is deep, and our brains are shallow.",
    nameVi: "Hãy học tập chăm chỉ, vì giếng sâu mà đầu óc chúng ta cạn.",
    tag: "depth",
  },
  {
    id: 83,
    name: "The only true wisdom is in knowing you know nothing.",
    nameVi: "Trí tuệ thực sự duy nhất là biết rằng mình không biết gì.",
    tag: "wisdom",
  },
  {
    id: 84,
    name: "Anyone who stops learning is old, whether at twenty or eighty.",
    nameVi: "Ai ngừng học tập đều già, dù ở tuổi hai mươi hay tám mươi.",
    tag: "aging",
  },
  {
    id: 85,
    name: "The best way to learn is to teach.",
    nameVi: "Cách tốt nhất để học là dạy.",
    tag: "teaching",
  },
  {
    id: 86,
    name: "Learning without application is just entertainment.",
    nameVi: "Học tập mà không ứng dụng chỉ là giải trí.",
    tag: "application",
  },
  {
    id: 87,
    name: "The expert in anything was once a beginner who refused to give up.",
    nameVi: "Chuyên gia trong bất kỳ lĩnh vực nào đều từng là người mới bắt đầu không chịu từ bỏ.",
    tag: "persistence",
  },
  {
    id: 88,
    name: "Learning is not a spectator sport.",
    nameVi: "Học tập không phải là môn thể thao dành cho khán giả.",
    tag: "participation",
  },
  {
    id: 89,
    name: "The mind is everything. What you think you become.",
    nameVi: "Tâm trí là tất cả. Những gì bạn nghĩ, bạn sẽ trở thành.",
    tag: "mindset",
  },
  {
    id: 90,
    name: "Education is learning what you didn't even know you didn't know.",
    nameVi: "Giáo dục là học những gì bạn thậm chí không biết mình không biết.",
    tag: "unknown",
  },
  {
    id: 91,
    name: "The more that you study, the more that you learn. The more that you learn, the more that you earn.",
    nameVi: "Bạn càng học nhiều, bạn càng học được nhiều. Bạn càng học được nhiều, bạn càng kiếm được nhiều.",
    tag: "value",
  },
  {
    id: 92,
    name: "Learning is a gift, even when pain is your teacher.",
    nameVi: "Học tập là một món quà, ngay cả khi đau khổ là giáo viên của bạn.",
    tag: "adversity",
  },
  {
    id: 93,
    name: "You are never too old to set another goal or to dream a new dream.",
    nameVi: "Bạn không bao giờ quá già để đặt ra một mục tiêu khác hoặc mơ một giấc mơ mới.",
    tag: "dreams",
  },
  {
    id: 94,
    name: "The only person who is educated is the one who has learned how to learn and change.",
    nameVi: "Người được giáo dục duy nhất là người đã học cách học và thay đổi.",
    tag: "adaptability",
  },
  {
    id: 95,
    name: "Success is walking from failure to failure with no loss of enthusiasm.",
    nameVi: "Thành công là đi từ thất bại này đến thất bại khác mà không mất đi sự nhiệt tình.",
    tag: "enthusiasm",
  },
  {
    id: 96,
    name: "The difference between school and life? In school, you're taught a lesson and then given a test. In life, you're given a test that teaches you a lesson.",
    nameVi:
      "Sự khác biệt giữa trường học và cuộc sống? Ở trường, bạn được dạy bài học rồi mới được kiểm tra. Trong cuộc sống, bạn được kiểm tra để học được bài học.",
    tag: "life_lessons",
  },
  {
    id: 97,
    name: "Don't let schooling interfere with your education.",
    nameVi: "Đừng để việc đi học cản trở giáo dục của bạn.",
    tag: "self_education",
  },
  {
    id: 98,
    name: "The moment you stop learning, you stop leading.",
    nameVi: "Khoảnh khắc bạn ngừng học là khoảnh khắc bạn ngừng dẫn dắt.",
    tag: "leadership",
  },
  {
    id: 99,
    name: "Education is what remains after one has forgotten what one has learned in school.",
    nameVi: "Giáo dục là thứ còn lại sau khi một người quên những gì đã học ở trường.",
    tag: "retention",
  },
  {
    id: 100,
    name: "The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.",
    nameVi: "Kẻ thù lớn nhất của kiến thức không phải là sự ngu dốt, mà là ảo tưởng về kiến thức.",
    tag: "illusion",
  },
  {
    id: 101,
    name: "I have never let my schooling interfere with my education.",
    nameVi: "Tôi chưa bao giờ để việc học ở trường can thiệp vào giáo dục của mình.",
    tag: "independence",
  },
  {
    id: 102,
    name: "Learning and innovation go hand in hand.",
    nameVi: "Học tập và đổi mới đi đôi với nhau.",
    tag: "innovation",
  },
  {
    id: 103,
    name: "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.",
    nameVi: "Khả năng học là một món quà; kỹ năng học là một tài năng; sự sẵn lòng học là một lựa chọn.",
    tag: "willingness",
  },
  {
    id: 104,
    name: "Never stop learning because life never stops teaching.",
    nameVi: "Đừng bao giờ ngừng học vì cuộc sống không bao giờ ngừng dạy.",
    tag: "continuous",
  },
  {
    id: 105,
    name: "The greatest sign of success for a teacher is to be able to say, 'The children are now working as if I did not exist.'",
    nameVi: "Dấu hiệu thành công lớn nhất của một giáo viên là có thể nói: 'Các em hiện đang học như thể tôi không tồn tại.'",
    tag: "independence",
  },
  {
    id: 106,
    name: "Real learning comes about when the competitive spirit has ceased.",
    nameVi: "Việc học tập thực sự xảy ra khi tinh thần cạnh tranh đã chấm dứt.",
    tag: "cooperation",
  },
  {
    id: 107,
    name: "The most important thing in life is to learn how to give out love, and to let it come in.",
    nameVi: "Điều quan trọng nhất trong cuộc sống là học cách cho đi tình yêu và để nó đến.",
    tag: "love",
  },
  {
    id: 108,
    name: "Learning is not compulsory... neither is survival.",
    nameVi: "Học tập không bắt buộc... sống sót cũng vậy.",
    tag: "survival",
  },
  {
    id: 109,
    name: "The goal of education is not to increase the amount of knowledge but to create the possibilities for a child to invent and discover.",
    nameVi: "Mục tiêu của giáo dục không phải là tăng lượng kiến thức mà là tạo ra khả năng cho trẻ em phát minh và khám phá.",
    tag: "discovery",
  },
  {
    id: 110,
    name: "I am not a teacher, but an awakener.",
    nameVi: "Tôi không phải là giáo viên, mà là người đánh thức.",
    tag: "awakening",
  },
  {
    id: 111,
    name: "The mind once enlightened cannot again become dark.",
    nameVi: "Tâm trí một khi được khai sáng không thể trở lại tăm tối.",
    tag: "enlightenment",
  },
  {
    id: 112,
    name: "Teaching is the profession that teaches all the other professions.",
    nameVi: "Giảng dạy là nghề dạy tất cả các nghề khác.",
    tag: "profession",
  },
  {
    id: 113,
    name: "Every child is an artist. The problem is staying an artist when you grow up.",
    nameVi: "Mọi đứa trẻ đều là nghệ sĩ. Vấn đề là làm sao vẫn là nghệ sĩ khi lớn lên.",
    tag: "creativity",
  },
  {
    id: 114,
    name: "I cannot teach anybody anything. I can only make them think.",
    nameVi: "Tôi không thể dạy ai bất cứ điều gì. Tôi chỉ có thể khiến họ suy nghĩ.",
    tag: "thinking",
  },
  {
    id: 115,
    name: "The more you read, the more things you will know. The more that you learn, the more places you'll go.",
    nameVi: "Bạn càng đọc nhiều, bạn sẽ biết càng nhiều điều. Bạn càng học nhiều, bạn sẽ đi được càng nhiều nơi.",
    tag: "exploration",
  },
  {
    id: 116,
    name: "A person who won't read has no advantage over one who can't read.",
    nameVi: "Người không chịu đọc không có lợi thế gì so với người không biết đọc.",
    tag: "reading",
  },
  {
    id: 117,
    name: "It is what we think we know already that often prevents us from learning.",
    nameVi: "Chính những gì chúng ta nghĩ mình đã biết thường ngăn cản chúng ta học tập.",
    tag: "preconceptions",
  },
  {
    id: 118,
    name: "The beautiful thing about learning is that nobody can take it away from you.",
    nameVi: "Điều tuyệt vời của việc học tập là không ai có thể lấy đi nó từ bạn.",
    tag: "ownership",
  },
  {
    id: 119,
    name: "Education is the most powerful weapon which you can use to change the world.",
    nameVi: "Giáo dục là vũ khí mạnh mẽ nhất mà bạn có thể sử dụng để thay đổi thế giới.",
    tag: "power",
  },
  {
    id: 120,
    name: "Learn from yesterday, live for today, hope for tomorrow.",
    nameVi: "Học từ hôm qua, sống cho hôm nay, hy vọng cho ngày mai.",
    tag: "time",
  },
  {
    id: 121,
    name: "Knowledge speaks, but wisdom listens.",
    nameVi: "Kiến thức nói, nhưng trí tuệ lắng nghe.",
    tag: "listening",
  },
  {
    id: 122,
    name: "The expert in anything was once a beginner.",
    nameVi: "Chuyên gia trong bất kỳ lĩnh vực nào cũng từng là người mới bắt đầu.",
    tag: "beginnings",
  },
  {
    id: 123,
    name: "Every moment is a fresh beginning.",
    nameVi: "Mọi khoảnh khắc đều là một khởi đầu mới.",
    tag: "fresh_start",
  },
  {
    id: 124,
    name: "The only way to make sense out of change is to plunge into it, move with it, and join the dance.",
    nameVi: "Cách duy nhất để hiểu được sự thay đổi là lao vào nó, di chuyển cùng nó và tham gia vào cuộc nhảy.",
    tag: "adaptation",
  },
  {
    id: 125,
    name: "Don't let your learning lead to knowledge. Let your learning lead to action.",
    nameVi: "Đừng để việc học của bạn dẫn đến kiến thức. Hãy để việc học của bạn dẫn đến hành động.",
    tag: "action",
  },
  {
    id: 126,
    name: "The day you stop learning is the day you start dying.",
    nameVi: "Ngày bạn ngừng học là ngày bạn bắt đầu chết.",
    tag: "vitality",
  },
  {
    id: 127,
    name: "Education is not the learning of facts, but the training of the mind to think.",
    nameVi: "Giáo dục không phải là việc học các sự kiện, mà là rèn luyện tâm trí để suy nghĩ.",
    tag: "mental_training",
  },
  {
    id: 128,
    name: "I am still learning.",
    nameVi: "Tôi vẫn đang học.",
    tag: "continuous_learning",
  },
  {
    id: 129,
    name: "The purpose of education is to replace an empty mind with an open one.",
    nameVi: "Mục đích của giáo dục là thay thế một tâm trí trống rỗng bằng một tâm trí cởi mở.",
    tag: "openness",
  },
  {
    id: 130,
    name: "Learning is the beginning of wealth. Learning is the beginning of health. Learning is the beginning of spirituality.",
    nameVi: "Học tập là khởi đầu của sự giàu có. Học tập là khởi đầu của sức khỏe. Học tập là khởi đầu của tâm linh.",
    tag: "holistic",
  },
  {
    id: 131,
    name: "The great aim of education is not knowledge but action.",
    nameVi: "Mục tiêu lớn của giáo dục không phải là kiến thức mà là hành động.",
    tag: "practical",
  },
  {
    id: 132,
    name: "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.",
    nameVi: "Trí tuệ không phải là sản phẩm của việc đi học mà là nỗ lực suốt đời để đạt được nó.",
    tag: "lifelong_pursuit",
  },
  {
    id: 133,
    name: "The more you learn, the more you earn.",
    nameVi: "Bạn càng học nhiều, bạn càng kiếm được nhiều.",
    tag: "earning",
  },
  {
    id: 134,
    name: "Education is the key to success in life, and teachers make a lasting impact in the lives of their students.",
    nameVi: "Giáo dục là chìa khóa thành công trong cuộc sống, và giáo viên tạo ra tác động lâu dài trong cuộc sống của học sinh.",
    tag: "impact",
  },
  {
    id: 135,
    name: "If you think education is expensive, try ignorance.",
    nameVi: "Nếu bạn nghĩ giáo dục đắt đỏ, hãy thử sự ngu dốt.",
    tag: "cost",
  },
  {
    id: 136,
    name: "The only true education is experience.",
    nameVi: "Giáo dục thực sự duy nhất là kinh nghiệm.",
    tag: "experience",
  },
  {
    id: 137,
    name: "Study the past if you would define the future.",
    nameVi: "Nghiên cứu quá khứ nếu bạn muốn định nghĩa tương lai.",
    tag: "history",
  },
  {
    id: 138,
    name: "The secret to getting ahead is getting started.",
    nameVi: "Bí mật để tiến lên phía trước là bắt đầu.",
    tag: "starting",
  },
  {
    id: 139,
    name: "You are what you choose to become.",
    nameVi: "Bạn là những gì bạn chọn để trở thành.",
    tag: "choice",
  },
  {
    id: 140,
    name: "The desire to learn is the key to learning.",
    nameVi: "Mong muốn học tập là chìa khóa của việc học tập.",
    tag: "desire",
  },
  {
    id: 141,
    name: "Learning gives creativity, creativity leads to thinking, thinking provides knowledge, knowledge makes you great.",
    nameVi: "Học tập mang lại sáng tạo, sáng tạo dẫn đến tư duy, tư duy cung cấp kiến thức, kiến thức làm bạn trở nên vĩ đại.",
    tag: "greatness",
  },
  {
    id: 142,
    name: "The foundation of every state is the education of its youth.",
    nameVi: "Nền tảng của mọi quốc gia là việc giáo dục giới trẻ.",
    tag: "foundation",
  },
  {
    id: 143,
    name: "Learning is not child's play; we cannot learn without pain.",
    nameVi: "Học tập không phải trò chơi trẻ con; chúng ta không thể học mà không có đau khổ.",
    tag: "struggle",
  },
  {
    id: 144,
    name: "It is the mark of an educated mind to be able to entertain a thought without accepting it.",
    nameVi: "Dấu hiệu của một trí tuệ được giáo dục là có thể tiếp nhận một ý tưởng mà không chấp nhận nó.",
    tag: "critical_thinking",
  },
  {
    id: 145,
    name: "The educated differ from the uneducated as much as the living differ from the dead.",
    nameVi: "Người được giáo dục khác với người không được giáo dục nhiều như người sống khác với người chết.",
    tag: "difference",
  },
  {
    id: 146,
    name: "Education is simply the soul of a society as it passes from one generation to another.",
    nameVi: "Giáo dục đơn giản là linh hồn của xã hội khi nó truyền từ thế hệ này sang thế hệ khác.",
    tag: "transmission",
  },
  {
    id: 147,
    name: "The aim of education is the knowledge not of facts but of values.",
    nameVi: "Mục tiêu của giáo dục là hiểu biết không phải về sự kiện mà về giá trị.",
    tag: "values",
  },
  {
    id: 148,
    name: "Learning without thinking is useless. Thinking without learning is dangerous.",
    nameVi: "Học mà không suy nghĩ thì vô ích. Suy nghĩ mà không học thì nguy hiểm.",
    tag: "balance",
  },
  {
    id: 149,
    name: "The best education I have ever received was through travel.",
    nameVi: "Nền giáo dục tốt nhất tôi từng nhận được là thông qua du lịch.",
    tag: "travel",
  },
  {
    id: 150,
    name: "Education is what survives when what has been learned has been forgotten.",
    nameVi: "Giáo dục là thứ tồn tại khi những gì đã học đã bị quên.",
    tag: "survival",
  },
  {
    id: 151,
    name: "The authority of those who teach is often an obstacle to those who want to learn.",
    nameVi: "Quyền uy của những người dạy thường là chướng ngại cho những người muốn học.",
    tag: "authority",
  },
  {
    id: 152,
    name: "Education is learning what you didn't even know you didn't know.",
    nameVi: "Giáo dục là học những gì bạn thậm chí không biết mình không biết.",
    tag: "unknown_unknowns",
  },
  {
    id: 153,
    name: "The one exclusive sign of thorough knowledge is the power of teaching.",
    nameVi: "Dấu hiệu duy nhất của kiến thức sâu sắc là khả năng giảng dạy.",
    tag: "mastery",
  },
  {
    id: 154,
    name: "Learning is experience. Everything else is just information.",
    nameVi: "Học tập là kinh nghiệm. Mọi thứ khác chỉ là thông tin.",
    tag: "experiential",
  },
  {
    id: 155,
    name: "The beautiful thing about learning is that no one can take it away from you.",
    nameVi: "Điều tuyệt vời của việc học tập là không ai có thể lấy đi nó từ bạn.",
    tag: "permanent",
  },
  {
    id: 156,
    name: "The price of success is hard work, dedication to the job at hand.",
    nameVi: "Cái giá của thành công là làm việc chăm chỉ, cống hiến cho công việc hiện tại.",
    tag: "dedication",
  },
  {
    id: 157,
    name: "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice.",
    nameVi: "Thành công không phải tình cờ. Đó là làm việc chăm chỉ, kiên trì, học tập, nghiên cứu, hy sinh.",
    tag: "ingredients",
  },
  {
    id: 158,
    name: "The road to success and the road to failure are almost exactly the same.",
    nameVi: "Con đường dẫn đến thành công và con đường dẫn đến thất bại gần như hoàn toàn giống nhau.",
    tag: "paths",
  },
  {
    id: 159,
    name: "Success is not how high you have climbed, but how you make a positive difference to the world.",
    nameVi: "Thành công không phải là bạn đã leo cao đến đâu, mà là cách bạn tạo ra sự khác biệt tích cực cho thế giới.",
    tag: "contribution",
  },
  {
    id: 160,
    name: "The successful warrior is the average man with laser-like focus.",
    nameVi: "Chiến binh thành công là người bình thường với sự tập trung như tia laser.",
    tag: "concentration",
  },
  {
    id: 161,
    name: "Success is not in what you have, but who you are.",
    nameVi: "Thành công không nằm ở những gì bạn có, mà ở con người bạn là ai.",
    tag: "identity",
  },
  {
    id: 162,
    name: "Don't be afraid to give up the good to go for the great.",
    nameVi: "Đừng sợ từ bỏ cái tốt để hướng đến cái tuyệt vời.",
    tag: "sacrifice",
  },
  {
    id: 163,
    name: "The way to get started is to quit talking and begin doing.",
    nameVi: "Cách để bắt đầu là ngừng nói và bắt đầu làm.",
    tag: "execution",
  },
  {
    id: 164,
    name: "Innovation distinguishes between a leader and a follower.",
    nameVi: "Đổi mới phân biệt giữa người lãnh đạo và người theo đuôi.",
    tag: "leadership",
  },
  {
    id: 165,
    name: "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.",
    nameVi: "Người bi quan thấy khó khăn trong mọi cơ hội. Người lạc quan thấy cơ hội trong mọi khó khăn.",
    tag: "perspective",
  },
  {
    id: 166,
    name: "Don't watch the clock; do what it does. Keep going.",
    nameVi: "Đừng nhìn đồng hồ; hãy làm những gì nó làm. Tiếp tục đi.",
    tag: "persistence",
  },
  {
    id: 167,
    name: "The future depends on what you do today.",
    nameVi: "Tương lai phụ thuộc vào những gì bạn làm hôm nay.",
    tag: "present_action",
  },
  {
    id: 168,
    name: "Strive not to be a success, but rather to be of value.",
    nameVi: "Hãy cố gắng không phải để thành công, mà để có giá trị.",
    tag: "value_creation",
  },
  {
    id: 169,
    name: "The only limit to our realization of tomorrow will be our doubts of today.",
    nameVi: "Giới hạn duy nhất cho việc thực hiện ngày mai sẽ là những nghi ngờ của ngày hôm nay.",
    tag: "doubt",
  },
  {
    id: 170,
    name: "It is never too late to be what you might have been.",
    nameVi: "Không bao giờ là quá muộn để trở thành những gì bạn có thể đã trở thành.",
    tag: "potential",
  },
  {
    id: 171,
    name: "Whether you think you can or you think you can't, you're right.",
    nameVi: "Dù bạn nghĩ bạn có thể hay bạn nghĩ bạn không thể, bạn đều đúng.",
    tag: "self_belief",
  },
  {
    id: 172,
    name: "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    nameVi: "Vinh quang lớn nhất trong cuộc sống không nằm ở việc không bao giờ ngã, mà ở việc đứng dậy mỗi khi chúng ta ngã.",
    tag: "resilience",
  },
  {
    id: 173,
    name: "Life is what happens to you while you're busy making other plans.",
    nameVi: "Cuộc sống là những gì xảy ra với bạn trong khi bạn bận rộn lập kế hoạch khác.",
    tag: "life_reality",
  },
  {
    id: 174,
    name: "The future belongs to those who believe in the beauty of their dreams.",
    nameVi: "Tương lai thuộc về những ai tin vào vẻ đẹp của ước mơ mình.",
    tag: "dream_belief",
  },
  {
    id: 175,
    name: "It is during our darkest moments that we must focus to see the light.",
    nameVi: "Chính trong những khoảnh khắc tăm tối nhất, chúng ta phải tập trung để thấy ánh sáng.",
    tag: "darkness_light",
  },
  {
    id: 176,
    name: "Whoever you are, be a good one.",
    nameVi: "Dù bạn là ai, hãy là một người tốt.",
    tag: "goodness",
  },
  {
    id: 177,
    name: "If you want to lift yourself up, lift up someone else.",
    nameVi: "Nếu bạn muốn nâng mình lên, hãy nâng người khác lên.",
    tag: "helping_others",
  },
  {
    id: 178,
    name: "Believe you can and you're halfway there.",
    nameVi: "Tin rằng bạn có thể và bạn đã đi được nửa chặng đường.",
    tag: "halfway",
  },
  {
    id: 179,
    name: "The only impossible journey is the one you never begin.",
    nameVi: "Hành trình bất khả thi duy nhất là hành trình bạn không bao giờ bắt đầu.",
    tag: "beginning",
  },
  {
    id: 180,
    name: "In the middle of difficulty lies opportunity.",
    nameVi: "Ở giữa khó khăn chính là cơ hội.",
    tag: "opportunity_in_difficulty",
  },
  {
    id: 181,
    name: "It does not matter how slowly you go as long as you do not stop.",
    nameVi: "Không quan trọng bạn đi chậm như thế nào miễn là bạn không dừng lại.",
    tag: "steady_progress",
  },
  {
    id: 182,
    name: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.",
    nameVi: "Điểm yếu lớn nhất của chúng ta nằm ở việc từ bỏ. Cách chắc chắn nhất để thành công là luôn thử thêm một lần nữa.",
    tag: "never_give_up",
  },
  {
    id: 183,
    name: "You miss 100% of the shots you don't take.",
    nameVi: "Bạn bỏ lỡ 100% những cú sút mà bạn không thực hiện.",
    tag: "taking_chances",
  },
]

export class QuoteService {
  private static instance: QuoteService

  public static getInstance(): QuoteService {
    if (!QuoteService.instance) {
      QuoteService.instance = new QuoteService()
    }
    return QuoteService.instance
  }

  getRandomQuote(): string {
    const randomIndex = Math.floor(Math.random() * quotes.length)
    return quotes[randomIndex].nameVi
  }
}
